# Generated by Django 2.2.6 on 2019-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=100, verbose_name='Nome_responsavel')),
                ('cpf_responsavel', models.IntegerField(verbose_name='Cpf_responsavel')),
                ('nome_escola', models.CharField(max_length=100, verbose_name='Nome_escola')),
                ('cep', models.IntegerField(verbose_name='cep')),
                ('telefone', models.CharField(max_length=255, verbose_name='telefone')),
                ('usuario', models.CharField(max_length=255, verbose_name='usuario')),
                ('senha', models.CharField(max_length=255, verbose_name='senha')),
            ],
        ),
    ]
