# Generated by Django 2.2.6 on 2019-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome_doacao')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
            ],
        ),
    ]
