# Generated by Django 2.2.6 on 2019-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome_doacao')),
                ('quantidade', models.IntegerField(verbose_name='quantidade')),
                ('descricao', models.CharField(max_length=255, verbose_name='descricao')),
            ],
        ),
        migrations.DeleteModel(
            name='Doador',
        ),
    ]
