# Generated by Django 2.2.6 on 2019-10-21 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Escola', '0001_initial'),
        ('doador', '0001_initial'),
        ('doacao', '0002_auto_20191021_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doador.Doador'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Escola.Escola'),
        ),
    ]
