# Generated by Django 2.2.6 on 2019-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome_doador')),
                ('idade', models.IntegerField(verbose_name='idade')),
                ('cpf', models.IntegerField(verbose_name='cpf')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('senha', models.CharField(max_length=255, verbose_name='senha')),
                ('cep', models.IntegerField(verbose_name='cep')),
            ],
        ),
    ]
